name: Devcontainer configuration

on:
  pull_request:
    branches:
      - main

jobs:
  build-devcontainer:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Build the repository devcontainer
        run: npx --yes @devcontainers/cli@0.89.0 build --workspace-folder . --log-level debug
